server:
  port: 8081

spring:
  application:
    name: ${APP_NAME:sub-server}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE:voddb}

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE}
  queue: ${RABBITMQ_QUEUE}
  routingkey: ${RABBITMQ_ROUTING_KEY}

icurff:
  app:
    storage: ${ICURFF_APP_STORAGE}
    location: ${ICURFF_APP_LOCATION}

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket: ${SUPABASE_BUCKET:images}

