global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Monitor Central Server
  - job_name: 'central-server'
    static_configs:
      - targets: ['13.214.164.43:9100']
        labels:
          server: 'central-server'

  # Monitor SubServer 1
  - job_name: 'subserver-1'
    static_configs:
      - targets: ['52.221.188.210:9100']
        labels:
          server: 'subserver-1'

  # Monitor SubServer 2
  - job_name: 'subserver-2'
    static_configs:
      - targets: ['13.212.183.23:9100']
        labels:
          server: 'subserver-2'

  # Monitor SubServer 3
  - job_name: 'subserver-3'
    static_configs:
      - targets: ['47.129.214.212:9100']
        labels:
          server: 'subserver-3'

