spring:
  application:
    name: ${APP_NAME:central-server}
  
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE:voddb}
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

icurff:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
    tokenExprirationSec: ${TOKEN_EXPIRATION_SEC:300}
    prometheusEndpoint: ${PROMETHEUS_ENDPOINT}

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL_SECURITY:DEBUG}

